name = "sesocell/conch_ui"
version = "0.2.5"
includes = ["src/**", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
vide = { wally = "wally#centau/vide", version = "^0.3.1" }
ast = { wally = "wally#alicesaidhi/conch-ast", version = "^0.2.1" }
conch = { wally = "wally#alicesaidhi/conch", version = "^0.2.4" }
